name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use whatever Node.js version your project requires

      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn generate

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: ghpages  # The branch the action should deploy to.
          folder: .output/public  # Adjusted to the new output folder for Nuxt 3
          token: ${{ secrets.GH_TOKEN }}  # GitHub token for authentication.
          repository: CNCF-Lahore/Kubernetes-Bootcamp  # Optional: defaults to the current repo.
          clean: true  # Optional: Cleans the deployment branch except for the .git directory.
